# Generated by Django 5.2.5 on 2026-09-17 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='SUPPLIER')),
                ('supplier_address', models.TextField(verbose_name='Address')),
                ('supplier_phone', models.CharField(max_length=10, verbose_name='CONTACT NO')),
                ('supplier_email', models.EmailField(max_length=254, verbose_name='SUPPLIER_EMAIL')),
                ('contact_person', models.CharField(max_length=50, verbose_name='CONTACT PERSON')),
                ('contact_person_phone', models.CharField(max_length=50, verbose_name='CONTACT PERSON PHONE')),
                ('contact_person_email', models.EmailField(max_length=254, verbose_name='CONTACT PERSON EMAIL')),
                ('equipment_rent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_size', models.CharField(blank=True, max_length=50, null=True)),
                ('boq_qty', models.PositiveIntegerField(default=1, verbose_name='BOQ Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boq_items', to='inventory.category')),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('boq_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boq_items', to='inventory.uom')),
            ],
            options={
                'verbose_name': 'BOQ Item',
                'verbose_name_plural': 'BOQ Items',
                'ordering': ['boq_item'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=25, unique=True, verbose_name='EQIPMNENT TYPE')),
                ('equipment_properties', models.TextField(blank=True, null=True, verbose_name='PROPERTIES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment types entry',
                'verbose_name_plural': 'Equipment types',
                'ordering': ['-equipment_type'],
                'indexes': [models.Index(fields=['equipment_type'], name='projects_eq_equipme_238605_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_no', models.CharField(max_length=5, null=True, unique=True, verbose_name='EQPT NO')),
                ('equipment_slno', models.CharField(max_length=15, null=True, unique=True, verbose_name='SLNO')),
                ('equipment_manufacture', models.CharField(max_length=30, null=True)),
                ('equipment_status', models.CharField(choices=[('Booked', 'Booked'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], db_column='EQUIPMENT STATUS', default='Booked', max_length=30, verbose_name='WORK STATUS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.equipmentsupplier')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_equipment', to='projects.equipmenttype', verbose_name='EQUIPMENT TYPE')),
            ],
            options={
                'verbose_name': 'Equipment entry',
                'verbose_name_plural': 'Equipments',
                'ordering': ['-equipment_no'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(db_column='PROJECT NO.', max_length=50, unique=True, verbose_name='PROJECT NO.')),
                ('client', models.CharField(blank=True, db_column='CLIENT', max_length=200, verbose_name='CLIENT')),
                ('project_title', models.CharField(blank=True, db_column='PROJECT TITLE', max_length=255, verbose_name='PROJECT TITLE')),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=255, verbose_name='LOCATION')),
                ('start_date', models.DateField(blank=True, db_column='START DATE', null=True, verbose_name='START DATE')),
                ('scope_of_work', models.TextField(blank=True, db_column='SCOPE OF WORK', verbose_name='SCOPE OF WORK')),
                ('project_type', models.CharField(choices=[('Instalaltion Only', 'Installation Only'), ('Supply Only', 'Supply Only'), ('Supply and Installation', 'Supply and Installation')], db_column='PROJECT TYPE', default='Instalaltion Only', max_length=30, verbose_name='PROJECT TYPE')),
                ('work_status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='WORK STATUS', default='Planning', max_length=30, verbose_name='WORK STATUS')),
                ('work_status_detail', models.TextField(blank=True, help_text='Original progress note from the source workbook.', verbose_name='WORK STATUS DETAIL')),
                ('remaining_work', models.TextField(blank=True, db_column='REMAINING WORK', verbose_name='REMAINING WORK')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date', 'project_no'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='DATE')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='STARTDATE')),
                ('activity', models.CharField(help_text='For example: Issued, Returned, Serviced', max_length=100, verbose_name='ACTIVITY')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='QUANTITY')),
                ('notes', models.TextField(blank=True, verbose_name='NOTES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_history', to='projects.project', verbose_name='PROJECT')),
            ],
            options={
                'verbose_name': 'Equipment history entry',
                'verbose_name_plural': 'Equipment history',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('working', 'Working'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending review', 'Pending Review')], max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=25)),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='DATE')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project', verbose_name='PROJECT')),
            ],
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='projects_eq_equipme_c0f315_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['work_status'], name='projects_pr_WORK ST_38926c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client'], name='projects_pr_CLIENT_720457_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='projects_pr_START D_c302bf_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenthistory',
            index=models.Index(fields=['project', 'entry_date'], name='projects_eq_project_1a9671_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenthistory',
            index=models.Index(fields=['equipment'], name='projects_eq_equipme_99dd75_idx'),
        ),
    ]
